# POST http://localhost:3000/api/auth/register
# Content-Type: application/json

# {
#   "nombre": "Alejandro",
#   "nickname": "Usuario 1",
#   "email": "cuenta2@gmail.com",
#   "password": "123456"
# }

# POST http://localhost:3000/api/auth/login
# Content-Type: application/json

# {
#   "email": "cuenta2@gmail.com",
#   "password": "123456"
# }

PUT http://localhost:3000/user/2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Mywicm9sZSI6ImNsaWVudGUiLCJpYXQiOjE3NjkyOTQ2ODQsImV4cCI6MTc2OTMwMTg4NH0.L_bIgWQLFNE8cpT-02ryVk9AeJINQgvi-DRyQQ_5zs4

{
  "nombre": "Luis",
  "nickname": "Luis123",
  "email": "luis123@gmail.com",
  "password": "1234567890"
}