# POST http://localhost:3000/user/purchases
# Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Mywicm9sZSI6ImNsaWVudGUiLCJpYXQiOjE3NzAyMjYwMTcsImV4cCI6MTc3MDIzMzIxN30.DPBO119plx0wp0bHvDhAN2RhNXIfZbIGgZoI3jh28qE

# {
#   "id_usuario": 1,
#   "id_juego": 3498,
#   "nombre": "Grand Theft Auto V",
#   "imagen_url": "https://example.com/gta5.jpg",
#   "precio": 59.99
# }

GET  http://localhost:3000/user/purchases/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Mywicm9sZSI6ImNsaWVudGUiLCJpYXQiOjE3NzAyMjYwMTcsImV4cCI6MTc3MDIzMzIxN30.DPBO119plx0wp0bHvDhAN2RhNXIfZbIGgZoI3jh28qE